import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import AutoComplete from "../components/AutoComplete";
import countries from "../components/AutoComplete/countries";
import { TextField } from "../components/TextField";
import styles from "../styles/Home.module.css";

const countriesArr = ["India", "China", "United States"];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />

        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin='true'
        />
      </Head>
      <div className={styles.component}>
        <div style={{ width: 400 }}>
        <h3>Autocomplete</h3>
          <AutoComplete
            options={countries}
            // getOptionLabel={(option) => option.code}
            // renderOption={(option) => (
            //   <li style={{display:"flex", gap:20, alignItems:"center", fontSize:14}}>
            //     <Image
            //       loading='lazy'
            //       width='20'
            //       height='20'
            //       src={`https://flagcdn.com/w20/${option.code.toLowerCase()}.png`}
            //       alt=''
            //     />
            //     {option.label} ({option.code}) + {option.phone}
            //   </li>
            // )}
            renderInput={(params) => {
              return <TextField placeholder='Choose a country' {...params} />;
            }}
          />
        </div>
      </div>
    </div>
  );
};

export default Home;
